baseURL: 'https://www.danieltperry.me/'
languageCode: 'en'
title: 'DanielTPerry.me'
theme: 'PaperMod'

params:
  assets:
    favicon: ico/favicon.ico
    favicon16x16: ico/favicon-16x16.png
    favicon32x32: ico/favicon-32x32.png
    apple_touch_icon: ico/apple-touch-icon.png
  profileMode:
    enabled: true
    title: "Daniel Tyler Perry"
    #subtitle: "[Website is still a work in progress]"
    buttons:
      - name: Blog Posts
        url: post/
      - name: Projects
        url: project/
      - name: Tags
        url: tags/
  
  #homeInfoParams:
  #  Title: "Daniel Tyler Perry"
  #  Content: >
  #      Welcome to my personal site.
  hideFooter: true
  socialIcons:
    - name: github
      title: "GitHub - netruk44"
      url: "https://github.com/netruk44"
    #- name: cv
    #  title: "Resume"
    #  url: "resume.pdf"
    - name: email
      url: "mailto:contact@danieltperry.me"
    - name: mastodon
      title: "Mastodon - @netruk44@fosstodon.org"
      url: "https://fosstodon.org/@netruk44"
    - name: tiktok
      title: "TikTok - @netruk44_dev"
      url: "https://www.tiktok.com/@netruk44_dev"
    - name: Rss
      url: "index.xml"

menu:
  main:
    - name: Blog
      weight: 1
      url: 'post/'
    - name: Projects
      weight: 2
      url: 'project/'
    #- name: Old Site
    #  weight: 999
    #  url: 'https://old.danieltperry.me/'
  
markup:
  goldmark:
    renderer:
      unsafe: true